#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
missing=0

fail() {
  echo "error: $1" >&2
  missing=1
}

require_path() {
  label="$1"
  rel="$2"
  if [ ! -e "$ROOT_DIR/$rel" ]; then
    fail "missing $label: $rel"
  fi
}

require_grep() {
  label="$1"
  pattern="$2"
  rel="$3"
  if ! grep -Fq -- "$pattern" "$ROOT_DIR/$rel"; then
    fail "missing $label in $rel: $pattern"
  fi
}

require_absent() {
  label="$1"
  pattern="$2"
  rel="$3"
  if grep -Fq -- "$pattern" "$ROOT_DIR/$rel"; then
    fail "unexpected $label in $rel: $pattern"
  fi
}

require_path "SideStore AltSign package" "ThirdParty/SideStore/AltSign"
require_path "SideStore minimuxer source" "ThirdParty/SideStore/minimuxer"
require_path "SideStore LocalDevVPN tunnel provider" "ThirdParty/SideStore/LocalDevVPN-TunnelProv"
require_path "SideStore full source clone" "ThirdParty/SideStore/Source/AltStore/TabBarController.swift"
require_path "SideStore AltStoreCore source" "ThirdParty/SideStore/Source/AltStoreCore"
require_path "SideStore AltWidget source" "ThirdParty/SideStore/Source/AltWidget"
require_path "SideStore app source" "ThirdParty/SideStore/Source/SideStore"
require_path "SideStore Shared source" "ThirdParty/SideStore/Source/Shared"
require_path "SideStore ci scripts source" "ThirdParty/SideStore/Source/scripts/ci"
require_path "Feather full source clone" "ThirdParty/Feather/Source/Feather/Views/Signing/SigningView.swift"
require_path "Feather AltSourceKit source" "ThirdParty/Feather/Source/AltSourceKit/Package.swift"
require_path "Feather Xcode project source" "ThirdParty/Feather/Source/Feather.xcodeproj/project.pbxproj"
require_path "Feather workspace source" "ThirdParty/Feather/Source/Feather.xcworkspace/contents.xcworkspacedata"
require_path "Feather images source" "ThirdParty/Feather/Source/Images/Image-dark.png"
require_path "Feather NimbleKit source" "ThirdParty/Feather/Source/NimbleKit/Package.swift"
require_path "LocalDevVPN full source clone" "ThirdParty/SideStore/LocalDevVPN-Source/TunnelProv/PacketTunnelProvider.swift"
require_path "Feather Zsign package" "ThirdParty/Feather/Zsign-Package"
require_path "SideStore source commit stamp" "ThirdParty/SideStore/Source/.litter-upstream-commit"
require_path "SideStore source submodule stamp" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_path "Feather source commit stamp" "ThirdParty/Feather/Source/.litter-upstream-commit"
require_path "Feather source submodule stamp" "ThirdParty/Feather/Source/.litter-submodules.txt"
require_path "LocalDevVPN source commit stamp" "ThirdParty/SideStore/LocalDevVPN-Source/.litter-upstream-commit"
require_path "SideStore source AltSign dependency" "ThirdParty/SideStore/Source/Dependencies/AltSign/Package.swift"
require_path "SideStore source AltSign ldid dependency" "ThirdParty/SideStore/Source/Dependencies/AltSign/Dependencies/ldid/ldid.cpp"
require_path "SideStore source AltSign ldid libplist dependency" "ThirdParty/SideStore/Source/Dependencies/AltSign/Dependencies/ldid/libplist/configure.ac"
require_path "SideStore source minimuxer dependency" "ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources/Minimuxer.swift"
require_path "SideStore source em_proxy dependency" "ThirdParty/SideStore/Source/Dependencies/em_proxy/Cargo.toml"
require_path "SideStore source apps-v2 dependency" "ThirdParty/SideStore/Source/Dependencies/apps-v2.json/index.json"
require_path "SideStore source Roxas dependency" "ThirdParty/SideStore/Source/Dependencies/Roxas/Roxas.podspec"
require_path "SideStore source MarkdownAttributedString dependency" "ThirdParty/SideStore/Source/Dependencies/MarkdownAttributedString/NSAttributedString+Markdown.m"
require_path "SideStore source libimobiledevice dependency" "ThirdParty/SideStore/Source/Dependencies/libimobiledevice/configure.ac"
require_path "SideStore source libplist dependency" "ThirdParty/SideStore/Source/Dependencies/libplist/configure.ac"
require_path "SideStore source libusbmuxd dependency" "ThirdParty/SideStore/Source/Dependencies/libusbmuxd/configure.ac"
require_path "SideStore source libimobiledevice-glue dependency" "ThirdParty/SideStore/Source/Dependencies/libimobiledevice-glue/configure.ac"
require_path "Feather source Zsign dependency" "ThirdParty/Feather/Source/Zsign/Package.swift"
require_path "Feather source IDeviceKitten dependency" "ThirdParty/Feather/Source/IDeviceKitten/Package.swift"
require_path "AltStore source verifier" "tools/scripts/verify-altstore-source.py"
require_path "BuildKit settings view" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_path "Feather signing settings view" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_path "Feather signing material store" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_path "SideStore account importer" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreAccountImport.swift"
require_path "SideStore signing bridge" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_path "SideStore minimuxer bridge" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_path "SideStore embedded factory" "apps/ios/Sources/SideStoreEmbedded/SideStoreEmbeddedFactory.swift"
require_path "SideStore host view" "apps/ios/Sources/Litter/Views/SideStoreHostView.swift"
if [ -e "$ROOT_DIR/apps/ios/Sources/Litter/Views/KittyStoreView.swift" ]; then
  fail "handmade KittyStore SwiftUI view is still present: apps/ios/Sources/Litter/Views/KittyStoreView.swift"
fi
require_path "KittyStore release source config" "apps/ios/Sources/Litter/Models/AppReleaseSource.swift"
require_path "Litter iOS Info plist" "apps/ios/Sources/Litter/Info.plist"
require_path "SideStore TabBarController app reference" "ThirdParty/SideStore/AppReference/AltStore/TabBarController.swift"
require_path "SideStore Browse app reference" "ThirdParty/SideStore/AppReference/AltStore/Browse/BrowseViewController.swift"
require_path "SideStore My Apps app reference" "ThirdParty/SideStore/AppReference/AltStore/My Apps/MyAppsViewController.swift"
require_path "SideStore Sources app reference" "ThirdParty/SideStore/AppReference/AltStore/Sources/SourcesViewController.swift"
require_path "SideStore Settings app reference" "ThirdParty/SideStore/AppReference/AltStore/Settings/SettingsViewController.swift"
require_path "Feather OptionsManager app reference" "ThirdParty/Feather/AppReference/Feather/Backend/Observable/OptionsManager.swift"
require_path "Feather SigningHandler app reference" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/SigningHandler.swift"
require_path "Feather TweakHandler app reference" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/TweakHandler.swift"
require_path "Feather ZsignHandler app reference" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/ZsignHandler.swift"
require_path "Feather SigningView app reference" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningView.swift"
require_path "Feather SigningProperties app reference" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningPropertiesView.swift"

require_grep "SideStore upstream commit provenance" "8485efe6c2f6f0fc1eb31cddc27c2abb4aa22d10" "ThirdParty/UPSTREAMS.md"
require_grep "Feather upstream commit provenance" "2320fd752864adaa9a173f9fc2f64ee9241e979e" "ThirdParty/UPSTREAMS.md"
require_grep "SideStore source exact commit stamp" "8485efe6c2f6f0fc1eb31cddc27c2abb4aa22d10" "ThirdParty/SideStore/Source/.litter-upstream-commit"
require_grep "Feather source exact commit stamp" "2320fd752864adaa9a173f9fc2f64ee9241e979e" "ThirdParty/Feather/Source/.litter-upstream-commit"
require_grep "LocalDevVPN source exact commit stamp" "c4566ce08931cef414c9f656e7e33c66bdb2454e" "ThirdParty/SideStore/LocalDevVPN-Source/.litter-upstream-commit"
require_grep "SideStore source AltSign exact commit" "a48493283bd676ad3a4d5b65dc7c039cebf7749e Dependencies/AltSign" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source AltSign ldid exact commit" "6a6a92de56ae2110e4d6f292b315df0f586d6af5 Dependencies/AltSign/Dependencies/ldid" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source AltSign ldid libplist exact commit" "17546f53ac1377b0d4f45a800aaec7366ba5b6a0 Dependencies/AltSign/Dependencies/ldid/libplist" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source minimuxer exact commit" "e3614068c77fb09945eff363fbc3f9e8abf4c834 Dependencies/minimuxer" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source em_proxy exact commit" "816dc73350dd456a24232963db77a3064fd9af8a Dependencies/em_proxy" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source apps-v2 exact commit" "9724b1c56d9c339ceefe2197abfbc026cd4cc1ff Dependencies/apps-v2.json" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source Roxas exact commit" "0784711ed9a3a0bdb5cc57bde35d2c621691cf74 Dependencies/Roxas" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source MarkdownAttributedString exact commit" "750e8d5cb455dcc592a9b6d1cacaa19837e7abff Dependencies/MarkdownAttributedString" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libimobiledevice exact commit" "e7cc53a65b0f975754760032015f58dfbb87e1a0 Dependencies/libimobiledevice" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libplist exact commit" "258d3c24aa05ade06aac4b5dd5148fd04c02893e Dependencies/libplist" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libusbmuxd exact commit" "30e678d4e76a9f4f8a550c34457dab73909bdd92 Dependencies/libusbmuxd" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libimobiledevice-glue exact commit" "214bafdde6a1434ead87357afe6cb41b32318495 Dependencies/libimobiledevice-glue" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "Feather source Zsign exact commit" "6ffe703df73ef9069adacdbb19d571f11a69a801 Zsign" "ThirdParty/Feather/Source/.litter-submodules.txt"
require_grep "Feather source IDeviceKitten exact commit" "837cf1e14d4875771dd5ee1b754a4c86215c5db3 IDeviceKitten" "ThirdParty/Feather/Source/.litter-submodules.txt"
require_grep "SideStore full source provenance" "SideStore full source snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "Feather full source provenance" "Feather full source snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "LocalDevVPN full source provenance" "LocalDevVPN full source snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "SideStore app reference provenance" "SideStore app layout reference snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "Feather app reference provenance" "Feather app reference snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "SideStore full source install path" "AppManager.shared.installAsync" "ThirdParty/SideStore/Source/AltStore/Browse/BrowseViewController.swift"
require_grep "Feather full source start signing" "Start Signing" "ThirdParty/Feather/Source/Feather/Views/Signing/SigningView.swift"
require_grep "LocalDevVPN full source tunnel provider" "PacketTunnelProvider" "ThirdParty/SideStore/LocalDevVPN-Source/TunnelProv/PacketTunnelProvider.swift"
require_grep "SideStore Browse reference install path" "AppManager.shared.installAsync" "ThirdParty/SideStore/AppReference/AltStore/Browse/BrowseViewController.swift"
require_grep "SideStore My Apps refresh reference" "AppManager.shared.refresh" "ThirdParty/SideStore/AppReference/AltStore/My Apps/MyAppsViewController.swift"
require_grep "SideStore Sources reference" "navigationItem.title" "ThirdParty/SideStore/AppReference/AltStore/Sources/SourcesViewController.swift"
require_grep "SideStore Settings certificate export reference" "SideStoreSigningCertificate.p12" "ThirdParty/SideStore/AppReference/AltStore/Settings/SettingsViewController.swift"
require_grep "Feather SigningView start button reference" "Start Signing" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningView.swift"
require_grep "Feather SigningView advanced options reference" "NavigationLink(.localized" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningView.swift"
require_grep "Feather Options remove files reference" "var removeFiles" "ThirdParty/Feather/AppReference/Feather/Backend/Observable/OptionsManager.swift"
require_grep "Feather Zsign reference" "Zsign.sign" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/ZsignHandler.swift"
require_grep "KittyStore runtime source config command" "litter-kittystore-config" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore source override persistence" "AppReleaseSource.saveOverrides" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore source override reset" "AppReleaseSource.clearOverrides" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore AppReleaseSource override keys" "ownerKey" "apps/ios/Sources/Litter/Models/AppReleaseSource.swift"
require_grep "Swift -e compatibility handler" "swift-e-check-ok" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "Swift frontend stderr capture" "Swift frontend stderr" "ThirdParty/Nyxian/CoreCompiler/Tools/Compiler/CCSwiftCompiler.cpp"
require_grep "Swift frontend no-diagnostic fallback" "Swift frontend returned a failure status without emitting diagnostics" "ThirdParty/Nyxian/CoreCompiler/Tools/Compiler/CCSwiftCompiler.cpp"
require_grep "Swift frontend storage diagnostics" "available storage is below the 6 GB recommended minimum" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "BuildKit status storage detail" "Available app storage" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit failed asset auto-install cache" "BuildKit.failed-auto-install.json" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit explicit install retries failed asset" "explicit install will retry" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit shim timeout writes status" "status=request-timeout" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit direct ZIP staging install" "try extractAssetZip(zipURL, to: stage)" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit ZIP root prefix stripping" "assetZipRootPrefix" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit single staged replacement" "replaceInstalledBuildKit(withStage" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_absent "BuildKit duplicate temp ZIP extraction" "LitterBuildKitZip-" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "AltSign dynamic package dependency" "AltSign-Dynamic" "apps/ios/project.yml"
require_grep "AltSign dynamic embed" "embed: true" "apps/ios/project.yml"
require_grep "SideStore framework target" "SideStore:" "apps/ios/project.yml"
require_grep "SideStore target compiles upstream AltStore" "../../ThirdParty/SideStore/Source/AltStore" "apps/ios/project.yml"
require_grep "SideStore target compiles upstream SideStore helpers" "../../ThirdParty/SideStore/Source/SideStore" "apps/ios/project.yml"
require_grep "AltStoreCore framework target" "AltStoreCore:" "apps/ios/project.yml"
require_grep "AltStoreCore target compiles upstream source" "../../ThirdParty/SideStore/Source/AltStoreCore" "apps/ios/project.yml"
require_grep "Roxas framework target" "Roxas:" "apps/ios/project.yml"
require_grep "Roxas prefix header" "Roxas-Prefix.pch" "apps/ios/project.yml"
require_grep "RustBridge framework target" "RustBridge:" "apps/ios/project.yml"
require_grep "Minimuxer framework target" "Minimuxer:" "apps/ios/project.yml"
require_grep "Minimuxer target compiles upstream source" "../../ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources" "apps/ios/project.yml"
require_grep "RustBridge target compiles upstream bridge" "../../ThirdParty/SideStore/Source/Dependencies/minimuxer/RustBridge" "apps/ios/project.yml"
require_grep "SideStore host routes real source UI" "SideStoreHostView()" "apps/ios/Sources/Litter/LitterApp.swift"
require_absent "KittyStore route still opens handmade SwiftUI store" "KittyStoreView()" "apps/ios/Sources/Litter/LitterApp.swift"
require_grep "SideStore host loads imported storyboard" "UIStoryboard(name: \"Main\"" "apps/ios/Sources/SideStoreEmbedded/SideStoreEmbeddedFactory.swift"
require_grep "SideStore host uses SideStore module bundle" "Bundle(for: AppDelegate.self)" "apps/ios/Sources/SideStoreEmbedded/SideStoreEmbeddedFactory.swift"
require_grep "Settings route opens Feather signing" "FeatherSigningSettingsView()" "apps/ios/Sources/Litter/Views/SettingsView.swift"
require_grep "Settings route enum includes signing" "case signing" "apps/ios/Sources/Litter/Views/SettingsView.swift"
require_grep "Feather signing stores upstream options key" "signing_options" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing validates p12" "NyxianSigningCertificateValidator.validate" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing validates mobileprovision" "NyxianProvisioningProfileValidator.validate" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing saves SideStore pairing path" "ALTPairingFile.mobiledevicepairing" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing saves Feather pairing path" "pairingFile.plist" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing LocalDevVPN launcher" "localdevvpn://enable?scheme=sidestore" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing start button" "Start Signing" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing frameworks UI" "Frameworks & PlugIns" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing reads SideStore account state" "Sign in from SideStore Settings" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing allows pfx certificate import" "litterPFX" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing allows mobiledevicepairing import" "litterMobileDevicePairing" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "IPA embeds full SideStore source folder" "../../ThirdParty/SideStore/Source" "apps/ios/project.yml"
require_grep "IPA embeds full Feather source folder" "../../ThirdParty/Feather/Source" "apps/ios/project.yml"
require_grep "IPA embeds full LocalDevVPN source folder" "../../ThirdParty/SideStore/LocalDevVPN-Source" "apps/ios/project.yml"
require_grep "IPA uses unique SideStore bundle destination" "copy_upstream_source SideStore" "apps/ios/project.yml"
require_grep "IPA uses unique Feather bundle destination" "copy_upstream_source Feather" "apps/ios/project.yml"
require_grep "IPA uses unique LocalDevVPN bundle destination" "copy_upstream_source LocalDevVPN" "apps/ios/project.yml"
require_grep "minimuxer bridge build" "tools/scripts/build-sidestore-minimuxer.sh" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "minimuxer linked Swift flag" "KITTYSTORE_MINIMUXER_LINKED" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "dynamic framework packaging guard" "Verify embedded dynamic frameworks" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "Private BuildKit native refresh" "refresh_native_driver_if_needed" "apps/ios/scripts/prepare-buildkit-assets.sh"
require_grep "Private BuildKit native rebuild script" "build-litter-buildkit-native.sh" "apps/ios/scripts/prepare-buildkit-assets.sh"
require_grep "Private BuildKit refreshed fingerprint" "nativeDriverSourceFingerprint" "apps/ios/scripts/prepare-buildkit-assets.sh"
require_grep "AltStore source verifier workflow gate" "verify-altstore-source.py" ".github/workflows/ios-unsigned-ipa.yml"

require_grep "KittyStore configurable release source" "AppReleaseSource.current" "apps/ios/Sources/Litter/Models/AppUpdateStore.swift"
require_grep "BuildKit configurable KittyStore source" "AppReleaseSource.current.stableSourceURLString" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_absent "hardcoded AppUpdateStore NightVibes repo URL" "github.com/NightVibes33/litter" "apps/ios/Sources/Litter/Models/AppUpdateStore.swift"
require_absent "hardcoded BuildKit KittyStore NightVibes repo URL" "github.com/NightVibes33/litter" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"

require_absent "BuildKit SideStore account UI scatter" "Import SideStore Account" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit Apple ID login UI scatter" "Login Apple ID" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit certificate import UI scatter" "Import SideStore Certificate" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit certificate handler scatter" "handleCertificateImport" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_grep "BuildKit keeps SideStore login embedded" "Apple ID sign-in and 2FA stay inside SideStore Settings" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit SideStore account handler scatter" "handleSideStoreAccountImport" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit Apple ID handler scatter" "saveNyxianAppleID" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_grep "BuildKit binary pairing plist normalization" "normalizedPairingFileContents" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "LocalDevVPN endpoint reachability state" "endpointReachable" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_absent "overbearing LocalDevVPN interface dump" "Found active tunnel interface(s)" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_absent "overbearing minimuxer not-ready copy" "SideStore minimuxer is linked but not ready yet" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_grep "BuildKit Apple ID LocalDevVPN gate" "LocalDevVPN is required for apple-id signing" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore iOS SideStore scheme" "<string>sidestore</string>" "apps/ios/Sources/Litter/Info.plist"
require_grep "KittyStore iOS AltStore scheme" "<string>altstore</string>" "apps/ios/Sources/Litter/Info.plist"
require_grep "KittyStore iOS LocalDevVPN scheme" "<string>localdevvpn</string>" "apps/ios/Sources/Litter/Info.plist"
require_grep "SideStore LocalDevVPN override IP" "10.7.0.1" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_grep "SideStore minimuxer retarget wrapper" "retargetUsbmuxdAddr" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore RustBridge CI build" "Building SideStore RustBridge for iOS device" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore RustBridge static library staging" "librust_bridge.a" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore LocalDevVPN connection probe" "testLocalDevVPNConnection" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore local_user preservation" "local_user" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreAccountImport.swift"
require_grep "SideStore adiPB preservation" "adiPB" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreAccountImport.swift"
require_grep "SideStore ADI status" "hasSideStoreADI" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_absent "obsolete SideStore .sideconf bot command" "litter-kittystore-import-sideconf" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"

require_grep "SideStore bridge certificate validation" "sidestore-certificate-validation-failed" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_grep "SideStore imported certificate IPA preparation" "prepareSideStoreImportedIdentitySigningInput" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_grep "SideStore signing metadata rewrite" "CFBundleShortVersionString" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_absent "SideStore imported certificate direct IPA copy signing" "try fileManager.copyItem(at: ipaURL, to: outputURL)" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_grep "Feather remove files plan" "removeFiles" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "Feather native remove files" "LBIKittyStoreRemoveAppFiles" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native appearance plist" "UIUserInterfaceStyle" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native minimum OS plist" "MinimumOSVersion" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native ProMotion plist" 'CADisableMinimumFrameDurationOnPhone"] = @YES' "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native injection path mapper" "LBIKittyStoreDylibLoadPath" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native inject into extensions" "LBIKittyStoreExtensionBundlePaths" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native injection failure status" "kittystore-dylib-injection-failed" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_absent "Feather native injection path unapplied warning" "recorded but not applied by this backend" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"

require_absent "README obsolete SideStore .sideconf docs" ".sideconf" "README.md"
require_grep "README SideStore tab shape docs" "News, Sources, Browse, My Apps, and Settings" "README.md"
require_grep "README full SideStore source docs" "ThirdParty/SideStore/Source" "README.md"
require_grep "README full Feather source docs" "ThirdParty/Feather/Source" "README.md"
require_grep "README full LocalDevVPN source docs" "ThirdParty/SideStore/LocalDevVPN-Source" "README.md"
require_grep "Notices full SideStore source" "ThirdParty/SideStore/Source" "THIRD_PARTY_NOTICES.md"
require_grep "Notices full Feather source" "ThirdParty/Feather/Source" "THIRD_PARTY_NOTICES.md"
require_grep "Notices full LocalDevVPN source" "ThirdParty/SideStore/LocalDevVPN-Source" "THIRD_PARTY_NOTICES.md"
require_grep "README real LocalDevVPN launcher" "localdevvpn://" "README.md"
require_grep "README LocalDevVPN and pairing hard requirement" "direct install/refresh/remove/list operations stay blocked until LocalDevVPN is enabled and a pairing file is imported" "README.md"
require_grep "README SideStore/Feather attribution" "SideStore, AltStore, Feather, LocalDevVPN" "README.md"
require_grep "README installable AltSource versions" "version-history first" "README.md"

if [ "$missing" -ne 0 ]; then
  exit 1
fi

echo "KittyStore SideStore/Feather integration wiring verified."
