#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
missing=0

fail() {
  echo "error: $1" >&2
  missing=1
}

require_path() {
  label="$1"
  rel="$2"
  if [ ! -e "$ROOT_DIR/$rel" ]; then
    fail "missing $label: $rel"
  fi
}

require_grep() {
  label="$1"
  pattern="$2"
  rel="$3"
  if ! grep -Fq -- "$pattern" "$ROOT_DIR/$rel"; then
    fail "missing $label in $rel: $pattern"
  fi
}

require_absent() {
  label="$1"
  pattern="$2"
  rel="$3"
  if grep -Fq -- "$pattern" "$ROOT_DIR/$rel"; then
    fail "unexpected $label in $rel: $pattern"
  fi
}

require_path "SideStore AltSign package" "ThirdParty/SideStore/AltSign"
require_path "KittyStore minimuxer source" "ThirdParty/SideStore/minimuxer"
require_path "SideStore LocalDevVPN tunnel provider" "ThirdParty/SideStore/LocalDevVPN-TunnelProv"
require_path "SideStore full source clone" "ThirdParty/SideStore/Source/AltStore/TabBarController.swift"
require_path "SideStore AltStoreCore source" "ThirdParty/SideStore/Source/AltStoreCore"
require_path "SideStore AltWidget source" "ThirdParty/SideStore/Source/AltWidget"
require_path "SideStore app source" "ThirdParty/SideStore/Source/SideStore"
require_path "SideStore Shared source" "ThirdParty/SideStore/Source/Shared"
require_path "SideStore ci scripts source" "ThirdParty/SideStore/Source/scripts/ci"
require_path "Feather full source clone" "ThirdParty/Feather/Source/Feather/Views/Signing/SigningView.swift"
require_path "Feather AltSourceKit source" "ThirdParty/Feather/Source/AltSourceKit/Package.swift"
require_path "Feather Xcode project source" "ThirdParty/Feather/Source/Feather.xcodeproj/project.pbxproj"
require_path "Feather workspace source" "ThirdParty/Feather/Source/Feather.xcworkspace/contents.xcworkspacedata"
require_path "Feather images source" "ThirdParty/Feather/Source/Images/Image-dark.png"
require_path "Feather NimbleKit source" "ThirdParty/Feather/Source/NimbleKit/Package.swift"
require_path "LocalDevVPN full source clone" "ThirdParty/SideStore/LocalDevVPN-Source/TunnelProv/PacketTunnelProvider.swift"
require_path "Feather Zsign package" "ThirdParty/Feather/Zsign-Package"
require_path "SideStore source commit stamp" "ThirdParty/SideStore/Source/.litter-upstream-commit"
require_path "SideStore source submodule stamp" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_path "Feather source commit stamp" "ThirdParty/Feather/Source/.litter-upstream-commit"
require_path "Feather source submodule stamp" "ThirdParty/Feather/Source/.litter-submodules.txt"
require_path "LocalDevVPN source commit stamp" "ThirdParty/SideStore/LocalDevVPN-Source/.litter-upstream-commit"
require_path "SideStore source AltSign dependency" "ThirdParty/SideStore/Source/Dependencies/AltSign/Package.swift"
require_path "SideStore source AltSign ldid dependency" "ThirdParty/SideStore/Source/Dependencies/AltSign/Dependencies/ldid/ldid.cpp"
require_path "SideStore source AltSign ldid libplist dependency" "ThirdParty/SideStore/Source/Dependencies/AltSign/Dependencies/ldid/libplist/configure.ac"
require_path "SideStore source minimuxer dependency" "ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources/Minimuxer.swift"
require_path "SideStore source em_proxy dependency" "ThirdParty/SideStore/Source/Dependencies/em_proxy/Cargo.toml"
require_path "SideStore source apps-v2 dependency" "ThirdParty/SideStore/Source/Dependencies/apps-v2.json/index.json"
require_path "SideStore source Roxas dependency" "ThirdParty/SideStore/Source/Dependencies/Roxas/Roxas.podspec"
require_path "SideStore source MarkdownAttributedString dependency" "ThirdParty/SideStore/Source/Dependencies/MarkdownAttributedString/NSAttributedString+Markdown.m"
require_path "SideStore source libimobiledevice dependency" "ThirdParty/SideStore/Source/Dependencies/libimobiledevice/configure.ac"
require_path "SideStore source libplist dependency" "ThirdParty/SideStore/Source/Dependencies/libplist/configure.ac"
require_path "SideStore source libusbmuxd dependency" "ThirdParty/SideStore/Source/Dependencies/libusbmuxd/configure.ac"
require_path "SideStore source libimobiledevice-glue dependency" "ThirdParty/SideStore/Source/Dependencies/libimobiledevice-glue/configure.ac"
require_path "Feather source Zsign dependency" "ThirdParty/Feather/Source/Zsign/Package.swift"
require_path "Feather source IDeviceKitten dependency" "ThirdParty/Feather/Source/IDeviceKitten/Package.swift"
require_path "AltStore source verifier" "tools/scripts/verify-altstore-source.py"
require_path "BuildKit settings view" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_path "Feather signing settings view" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_path "Feather signing material store" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_path "Feather upstream option adapter" "apps/ios/Sources/Litter/Models/FeatherSigningUpstreamAdapter.swift"
require_path "SideStore account importer" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreAccountImport.swift"
require_path "SideStore signing bridge" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_path "KittyStore Nuke compatibility glue" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreNukeCompatibility.swift"
require_path "KittyStore minimuxer bridge" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_path "KittyStore embedded factory" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_path "KittyStore host view" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
if [ -e "$ROOT_DIR/apps/ios/Sources/Litter/Views/KittyStoreView.swift" ]; then
  fail "handmade KittyStore SwiftUI view is still present: apps/ios/Sources/Litter/Views/KittyStoreView.swift"
fi
require_path "KittyStore release source config" "apps/ios/Sources/Litter/Models/AppReleaseSource.swift"
require_path "Litter iOS Info plist" "apps/ios/Sources/Litter/Info.plist"
require_path "SideStore TabBarController app reference" "ThirdParty/SideStore/AppReference/AltStore/TabBarController.swift"
require_path "SideStore Browse app reference" "ThirdParty/SideStore/AppReference/AltStore/Browse/BrowseViewController.swift"
require_path "SideStore My Apps app reference" "ThirdParty/SideStore/AppReference/AltStore/My Apps/MyAppsViewController.swift"
require_path "SideStore Sources app reference" "ThirdParty/SideStore/AppReference/AltStore/Sources/SourcesViewController.swift"
require_path "SideStore Settings app reference" "ThirdParty/SideStore/AppReference/AltStore/Settings/SettingsViewController.swift"
require_path "Feather OptionsManager app reference" "ThirdParty/Feather/AppReference/Feather/Backend/Observable/OptionsManager.swift"
require_path "Feather SigningHandler app reference" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/SigningHandler.swift"
require_path "Feather TweakHandler app reference" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/TweakHandler.swift"
require_path "Feather ZsignHandler app reference" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/ZsignHandler.swift"
require_path "Feather SigningView app reference" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningView.swift"
require_path "Feather SigningProperties app reference" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningPropertiesView.swift"

require_grep "SideStore upstream commit provenance" "8485efe6c2f6f0fc1eb31cddc27c2abb4aa22d10" "ThirdParty/UPSTREAMS.md"
require_grep "Feather upstream commit provenance" "2320fd752864adaa9a173f9fc2f64ee9241e979e" "ThirdParty/UPSTREAMS.md"
require_grep "SideStore source exact commit stamp" "8485efe6c2f6f0fc1eb31cddc27c2abb4aa22d10" "ThirdParty/SideStore/Source/.litter-upstream-commit"
require_grep "Feather source exact commit stamp" "2320fd752864adaa9a173f9fc2f64ee9241e979e" "ThirdParty/Feather/Source/.litter-upstream-commit"
require_grep "LocalDevVPN source exact commit stamp" "c4566ce08931cef414c9f656e7e33c66bdb2454e" "ThirdParty/SideStore/LocalDevVPN-Source/.litter-upstream-commit"
require_grep "SideStore source AltSign exact commit" "a48493283bd676ad3a4d5b65dc7c039cebf7749e Dependencies/AltSign" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source AltSign ldid exact commit" "6a6a92de56ae2110e4d6f292b315df0f586d6af5 Dependencies/AltSign/Dependencies/ldid" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source AltSign ldid libplist exact commit" "17546f53ac1377b0d4f45a800aaec7366ba5b6a0 Dependencies/AltSign/Dependencies/ldid/libplist" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source minimuxer exact commit" "e3614068c77fb09945eff363fbc3f9e8abf4c834 Dependencies/minimuxer" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source em_proxy exact commit" "816dc73350dd456a24232963db77a3064fd9af8a Dependencies/em_proxy" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source apps-v2 exact commit" "9724b1c56d9c339ceefe2197abfbc026cd4cc1ff Dependencies/apps-v2.json" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source Roxas exact commit" "0784711ed9a3a0bdb5cc57bde35d2c621691cf74 Dependencies/Roxas" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source MarkdownAttributedString exact commit" "750e8d5cb455dcc592a9b6d1cacaa19837e7abff Dependencies/MarkdownAttributedString" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libimobiledevice exact commit" "e7cc53a65b0f975754760032015f58dfbb87e1a0 Dependencies/libimobiledevice" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libplist exact commit" "258d3c24aa05ade06aac4b5dd5148fd04c02893e Dependencies/libplist" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libusbmuxd exact commit" "30e678d4e76a9f4f8a550c34457dab73909bdd92 Dependencies/libusbmuxd" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "SideStore source libimobiledevice-glue exact commit" "214bafdde6a1434ead87357afe6cb41b32318495 Dependencies/libimobiledevice-glue" "ThirdParty/SideStore/Source/.litter-submodules.txt"
require_grep "Feather source Zsign exact commit" "6ffe703df73ef9069adacdbb19d571f11a69a801 Zsign" "ThirdParty/Feather/Source/.litter-submodules.txt"
require_grep "Feather source IDeviceKitten exact commit" "837cf1e14d4875771dd5ee1b754a4c86215c5db3 IDeviceKitten" "ThirdParty/Feather/Source/.litter-submodules.txt"
require_grep "SideStore full source provenance" "SideStore full source snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "Feather full source provenance" "Feather full source snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "LocalDevVPN full source provenance" "LocalDevVPN full source snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "SideStore app reference provenance" "SideStore app layout reference snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "Feather app reference provenance" "Feather app reference snapshot path" "ThirdParty/UPSTREAMS.md"
require_grep "SideStore full source install path" "AppManager.shared.installAsync" "ThirdParty/SideStore/Source/AltStore/Browse/BrowseViewController.swift"
require_grep "Feather full source start signing" "Start Signing" "ThirdParty/Feather/Source/Feather/Views/Signing/SigningView.swift"
require_grep "LocalDevVPN full source tunnel provider" "PacketTunnelProvider" "ThirdParty/SideStore/LocalDevVPN-Source/TunnelProv/PacketTunnelProvider.swift"
require_grep "SideStore Browse reference install path" "AppManager.shared.installAsync" "ThirdParty/SideStore/AppReference/AltStore/Browse/BrowseViewController.swift"
require_grep "SideStore My Apps refresh reference" "AppManager.shared.refresh" "ThirdParty/SideStore/AppReference/AltStore/My Apps/MyAppsViewController.swift"
require_grep "SideStore Sources reference" "navigationItem.title" "ThirdParty/SideStore/AppReference/AltStore/Sources/SourcesViewController.swift"
require_grep "SideStore Settings certificate export reference" "SideStoreSigningCertificate.p12" "ThirdParty/SideStore/AppReference/AltStore/Settings/SettingsViewController.swift"
require_grep "Feather SigningView start button reference" "Start Signing" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningView.swift"
require_grep "Feather SigningView advanced options reference" "NavigationLink(.localized" "ThirdParty/Feather/AppReference/Feather/Views/Signing/SigningView.swift"
require_grep "Feather Options remove files reference" "var removeFiles" "ThirdParty/Feather/AppReference/Feather/Backend/Observable/OptionsManager.swift"
require_grep "Feather Zsign reference" "Zsign.sign" "ThirdParty/Feather/AppReference/Feather/Utilities/Handlers/ZsignHandler.swift"
require_grep "KittyStore runtime source config command" "litter-kittystore-config" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore source override persistence" "AppReleaseSource.saveOverrides" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore source override reset" "AppReleaseSource.clearOverrides" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore AppReleaseSource override keys" "ownerKey" "apps/ios/Sources/Litter/Models/AppReleaseSource.swift"
require_grep "Swift -e compatibility handler" "swift-e-check-ok" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "Swift frontend stderr capture" "Swift frontend stderr" "ThirdParty/Nyxian/CoreCompiler/Tools/Compiler/CCSwiftCompiler.cpp"
require_grep "Swift frontend no-diagnostic fallback" "Swift frontend returned a failure status without emitting diagnostics" "ThirdParty/Nyxian/CoreCompiler/Tools/Compiler/CCSwiftCompiler.cpp"
require_grep "Swift frontend storage diagnostics" "available storage is below the 6 GB recommended minimum" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "BuildKit status storage detail" "Available app storage" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit failed asset auto-install cache" "BuildKit.failed-auto-install.json" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit explicit install retries failed asset" "explicit install will retry" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit shim timeout writes status" "status=request-timeout" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit direct ZIP staging install" "try extractAssetZip(zipURL, to: stage)" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit ZIP root prefix stripping" "assetZipRootPrefix" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "BuildKit single staged replacement" "replaceInstalledBuildKit(withStage" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_absent "BuildKit duplicate temp ZIP extraction" "LitterBuildKitZip-" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "AltSign dynamic package dependency" "AltSign-Dynamic" "apps/ios/project.yml"
require_grep "AltSign dynamic embed" "embed: true" "apps/ios/project.yml"
require_grep "SideStore framework target" "SideStore:" "apps/ios/project.yml"
require_grep "SideStore target compiles upstream AltStore" "../../ThirdParty/SideStore/Source/AltStore" "apps/ios/project.yml"
require_grep "SideStore target compiles upstream SideStore helpers" "../../ThirdParty/SideStore/Source/SideStore" "apps/ios/project.yml"
require_grep "SideStore target explicitly embeds Main storyboard" "Base.lproj/Main.storyboard" "apps/ios/project.yml"
require_grep "SideStore target explicitly embeds Settings storyboard" "Settings/Settings.storyboard" "apps/ios/project.yml"
require_grep "SideStore target explicitly embeds resources asset catalog" "Resources/Assets.xcassets" "apps/ios/project.yml"
require_grep "SideStore resources use XcodeGen resource build phase" "buildPhase: resources" "apps/ios/project.yml"
require_grep "AltStoreCore framework target" "AltStoreCore:" "apps/ios/project.yml"
require_grep "AltStoreCore target compiles upstream source" "../../ThirdParty/SideStore/Source/AltStoreCore" "apps/ios/project.yml"
require_grep "Roxas framework target" "Roxas:" "apps/ios/project.yml"
require_grep "Roxas prefix header" "Roxas-Prefix.pch" "apps/ios/project.yml"
require_grep "RustBridge framework target" "RustBridge:" "apps/ios/project.yml"
require_grep "Minimuxer framework target" "Minimuxer:" "apps/ios/project.yml"
require_grep "Minimuxer target compiles upstream source" "../../ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources" "apps/ios/project.yml"
require_grep "RustBridge target compiles upstream bridge" "../../ThirdParty/SideStore/Source/Dependencies/minimuxer/RustBridge" "apps/ios/project.yml"
require_grep "SideStore host routes real source UI" "KittyStoreRouteView()" "apps/ios/Sources/Litter/LitterApp.swift"
require_absent "KittyStore route still opens handmade SwiftUI store" "KittyStoreView()" "apps/ios/Sources/Litter/LitterApp.swift"
require_grep "KittyStore host loads imported storyboard" "UIStoryboard(name: \"Main\"" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore host uses SideStore module bundle" "Bundle(for: AppDelegate.self)" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore background audio uses framework bundle" "Bundle(for: BackgroundTaskManager.self)" "ThirdParty/SideStore/Source/AltStore/Components/BackgroundTaskManager.swift"
require_absent "KittyStore background color no longer force unwraps asset" 'UIColor(named: "Background", in: altStoreBundle, compatibleWith: nil)!' "ThirdParty/SideStore/Source/AltStore/Extensions/UIColor+AltStore.swift"
require_absent "KittyStore authentication color no longer force unwraps asset" 'UIColor(named: "SettingsHighlighted", in: Bundle(for: AppDelegate.self), compatibleWith: nil)!' "ThirdParty/SideStore/Source/AltStore/Operations/AuthenticationOperation.swift"
require_absent "KittyStore Browse does not load storyboard from main app bundle" 'UIStoryboard(name: "Main", bundle: .main)' "ThirdParty/SideStore/Source/AltStore/Browse/BrowseViewController.swift"
require_absent "KittyStore AddSource does not load storyboard from main app bundle" 'UIStoryboard(name: "Sources", bundle: .main)' "ThirdParty/SideStore/Source/AltStore/Sources/AddSourceViewController.swift"
require_absent "KittyStore Screenshots does not load storyboard from main app bundle" 'UIStoryboard(name: "Main", bundle: .main)' "ThirdParty/SideStore/Source/AltStore/App Detail/Screenshots/AppScreenshotsViewController.swift"
require_absent "KittyStore background audio no longer force unwraps main bundle Silence" 'Bundle.main.url(forResource: "Silence", withExtension: "m4a")!' "ThirdParty/SideStore/Source/AltStore/Components/BackgroundTaskManager.swift"
require_absent "KittyStore does not rely on generated asset color symbols" "UIColor(resource:" "ThirdParty/SideStore/Source/AltStore/Permissions/ReviewPermissionsViewController.swift"
require_absent "KittyStore logging settings does not rely on generated asset color symbols" "Color(.settingsBackground" "ThirdParty/SideStore/Source/AltStore/Settings/OperationsLoggingContolView.swift"
require_grep "KittyStore Nuke 12 URL loader compatibility" "func loadImage(" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreNukeCompatibility.swift"
require_grep "Settings route opens Feather signing" "FeatherSigningSettingsView()" "apps/ios/Sources/Litter/Views/SettingsView.swift"
require_grep "Settings route enum includes signing" "case signing" "apps/ios/Sources/Litter/Views/SettingsView.swift"
require_grep "Feather signing stores upstream options key" "signing_options" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing upstream options adapter reference" "OptionsManager.swift" "apps/ios/Sources/Litter/Models/FeatherSigningUpstreamAdapter.swift"
require_grep "Feather signing plan exports upstream options" "FeatherSigningUpstreamAdapter.optionsPayload" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "BuildKit KittyStore plan exports upstream options" "FeatherSigningUpstreamAdapter.optionsPayload" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore source long press menu" "contextMenuConfigurationForItemAt" "ThirdParty/SideStore/Source/AltStore/Sources/SourcesViewController.swift"
require_grep "KittyStore source refresh action" "Refresh Source" "ThirdParty/SideStore/Source/AltStore/Sources/SourcesViewController.swift"
require_grep "KittyStore source edit action" "Edit Source" "ThirdParty/SideStore/Source/AltStore/Sources/SourcesViewController.swift"
require_grep "Feather signing validates p12" "NyxianSigningCertificateValidator.validate" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing validates mobileprovision" "NyxianProvisioningProfileValidator.validate" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing saves SideStore pairing path" "ALTPairingFile.mobiledevicepairing" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing saves Feather pairing path" "pairingFile.plist" "apps/ios/Sources/Litter/Models/FeatherSigningMaterialStore.swift"
require_grep "Feather signing LocalDevVPN launcher" "localdevvpn://enable?scheme=sidestore" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing start button" "Start Signing" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing install signed IPA prompt" "Install Signed IPA" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing plain picker rows" ".buttonStyle(.plain)" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing frameworks UI" "Frameworks & PlugIns" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing reads KittyStore account state" "Sign in from KittyStore Settings" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing allows pfx certificate import" "litterPFX" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing allows mobiledevicepairing import" "litterMobileDevicePairing" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_absent "Feather signing no longer uses SwiftUI fileImporter" ".fileImporter" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing uses UIKit document picker" "UIDocumentPickerViewController" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing certificate picker label" "Import Certificate File" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "Feather signing provision picker label" "Import Provisioning File" "apps/ios/Sources/Litter/Views/FeatherSigningSettingsView.swift"
require_grep "IPA embeds full SideStore source folder" "../../ThirdParty/SideStore/Source" "apps/ios/project.yml"
require_grep "IPA embeds full Feather source folder" "../../ThirdParty/Feather/Source" "apps/ios/project.yml"
require_grep "IPA embeds full LocalDevVPN source folder" "../../ThirdParty/SideStore/LocalDevVPN-Source" "apps/ios/project.yml"
require_grep "IPA uses unique KittyStore bundle destination" "copy_upstream_source KittyStore" "apps/ios/project.yml"
require_grep "IPA uses unique Feather bundle destination" "copy_upstream_source Feather" "apps/ios/project.yml"
require_grep "IPA uses unique LocalDevVPN bundle destination" "copy_upstream_source LocalDevVPN" "apps/ios/project.yml"
require_grep "minimuxer bridge build" "tools/scripts/build-sidestore-minimuxer.sh" ".github/workflows/ios-unsigned-ipa.yml"
require_absent "release build does not enable Litter minimuxer bridge" 'KITTYSTORE_MINIMUXER_SWIFT_FLAGS="-D KITTYSTORE_MINIMUXER_LINKED"' ".github/workflows/ios-unsigned-ipa.yml"
require_absent "release build does not statically link minimuxer into Litter" 'KITTYSTORE_MINIMUXER_LDFLAGS="-lminimuxer-ios' ".github/workflows/ios-unsigned-ipa.yml"
require_absent "project does not expose global minimuxer linker switch" "KITTYSTORE_MINIMUXER_LDFLAGS" "apps/ios/project.yml"
require_absent "project does not expose global minimuxer Swift switch" "KITTYSTORE_MINIMUXER_SWIFT_FLAGS" "apps/ios/project.yml"
if ! awk '
  /^  Litter:/ { in_target = 1; next }
  in_target && /^  [^ ].*:/ { in_target = 0 }
  in_target && /^      - path: Sources\/Litter$/ { in_litter_sources = 1; next }
  in_litter_sources && /^      - path:/ { in_litter_sources = 0 }
  in_litter_sources && /^    [A-Za-z0-9_]+:/ { in_litter_sources = 0 }
  in_litter_sources && /- Generated\/Minimuxer\/\*\*/ { found = 1 }
  END { exit found ? 0 : 1 }
' "$ROOT_DIR/apps/ios/project.yml"; then
  fail "iOS Litter target must exclude generated KittyStore minimuxer bridge sources"
fi
require_grep "KittyStore framework targets own native link flags" "-lminimuxer-ios" "apps/ios/project.yml"
require_grep "RustBridge owns native minimuxer dependency" "-lrust_bridge -lminimuxer-ios" "apps/ios/project.yml"
require_grep "CI rejects Litter static minimuxer link" "Litter main executable links the KittyStore minimuxer static library" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "dynamic framework packaging guard" "Verify embedded dynamic frameworks" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "launch-linked iOS minOS guard" "verify_ios_minos" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "archive rejects newer iOS object warnings" "was built for newer 'iOS' version" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "minimuxer explicit iOS deployment target" "LITTER_MINIMUXER_MIN_IOS" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "Litter eagerly prepares KittyStore defaults like 1.5.52" "KittyStoreEmbeddedBridge.bootstrap()" "apps/ios/Sources/Litter/LitterApp.swift"
require_grep "KittyStore still prepares defaults from store runtime" "KittyStoreEmbeddedRuntime.prepareForLaunch()" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_absent "Litter app avoids Swift SideStore import autolink" "import SideStore" "apps/ios/Sources/Litter/LitterApp.swift"
require_grep "Litter app delegate stays native without SideStore superclass" "class AppDelegate: NSObject, UIApplicationDelegate" "apps/ios/Sources/Litter/LitterApp.swift"
require_absent "KittyStore host avoids Swift SideStore import autolink" "import SideStore" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore host calls runtime embedded bridge" "KittyStoreEmbeddedBridge.makeRootViewController()" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore host starts transport on entry" "KittyStoreEmbeddedBridge.startTransportIfPossible()" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore theme bridge exports background token" '("background", lightTheme.background, darkTheme.background)' "apps/ios/Sources/Litter/Models/ThemeManager.swift"
require_grep "KittyStore host reads Litter theme version" "themeManager.themeVersion" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore host applies embedded theme refresh" "KittyStoreEmbeddedBridge.applyCurrentTheme(to:" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore AltStoreCore theme defaults bridge" "LitterSharedThemeColors" "ThirdParty/SideStore/Source/AltStoreCore/Extensions/UIColor+AltStore.swift"
require_grep "KittyStore SideStore background uses Litter theme" "LitterSharedThemeColors.background" "ThirdParty/SideStore/Source/AltStore/Extensions/UIColor+AltStore.swift"
require_grep "KittyStore SideStore accent uses Litter theme" "LitterSharedThemeColors.accentStrong" "ThirdParty/SideStore/Source/AltStore/Extensions/UIColor+AltStore.swift"
require_grep "KittyStore embedded exposes theme refresh" "public static func applyCurrentTheme" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore route uses non-overlapping header layout" "VStack(spacing: 0)" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore route fills bottom safe area" "ignoresSafeArea(.container, edges: .bottom)" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_absent "KittyStore host no longer uses Objective-C dynamic loader" "KittyStoreDynamicLoader" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore runtime resource preflight" "resourcePreflightError" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "CI verifies KittyStore storyboard resource" "Main.storyboardc" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "CI verifies KittyStore Core Data resource" "AltStore.momd" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "KittyStore dynamic framework entry point" "KittyStoreEmbeddedEntryPoint" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "Litter runtime bridge resolves embedded KittyStore framework" "NSClassFromString" "apps/ios/Sources/Litter/Models/KittyStoreEmbeddedBridge.swift"
require_grep "KittyStore minimuxer transport entry point" "KittyStoreMinimuxerTransportEntryPoint" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_absent "Litter ObjC bridge avoids Minimuxer header autolink" "Minimuxer/" "apps/ios/Sources/Litter/Bridge/codex_bridge_objc.h"
require_grep "Litter embeds KittyStore framework" "- target: SideStore" "apps/ios/project.yml"
require_absent "Litter SideStore dependency does not disable linking" "link: false" "apps/ios/project.yml"
require_grep "CI requires direct Litter SideStore framework link" "@rpath/SideStore.framework/SideStore" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "CI rejects direct Litter minimuxer framework links" "keep minimuxer isolated behind the KittyStore framework" ".github/workflows/ios-unsigned-ipa.yml"
require_grep "Private BuildKit native refresh" "refresh_native_driver_if_needed" "apps/ios/scripts/prepare-buildkit-assets.sh"
require_grep "Private BuildKit native rebuild script" "build-litter-buildkit-native.sh" "apps/ios/scripts/prepare-buildkit-assets.sh"
require_grep "Private BuildKit refreshed fingerprint" "nativeDriverSourceFingerprint" "apps/ios/scripts/prepare-buildkit-assets.sh"
require_grep "AltStore source verifier workflow gate" "verify-altstore-source.py" ".github/workflows/ios-unsigned-ipa.yml"

require_grep "KittyStore default source follows SideStore" "https://sidestore.io/apps-v2.json/" "ThirdParty/SideStore/Source/AltStoreCore/Model/Source.swift"
require_absent "KittyStore source model does not hardcode Litter release source" "https://github.com/NightVibes33/litter/releases/download/app-source/litter-altstore-source.json" "ThirdParty/SideStore/Source/AltStoreCore/Model/Source.swift"
require_grep "KittyStore recommended source includes Litter" "https://github.com/NightVibes33/litter/releases/download/app-source/litter-altstore-source.json" "ThirdParty/SideStore/Source/trustedapps.json"
require_grep "KittyStore recommended source includes SideStore" "https://sidestore.io/apps-v2.json/" "ThirdParty/SideStore/Source/trustedapps.json"
require_grep "KittyStore add-source placeholder follows SideStore" "apps.sidestore.io" "ThirdParty/SideStore/Source/AltStore/Sources/Components/AddSourceTextFieldCell.swift"
require_grep "KittyStore embedded does not protect recommended sources" "!InstalledApp.hidesEmbeddedHostApps" "ThirdParty/SideStore/Source/AltStoreCore/Model/Source.swift"
require_grep "KittyStore source list uses removable-source helper" "Source.isProtectedDefaultSource(source)" "ThirdParty/SideStore/Source/AltStore/Sources/SourcesViewController.swift"
require_grep "KittyStore source removal uses removable-source helper" "Source.isProtectedDefaultSourceID(sourceID)" "ThirdParty/SideStore/Source/AltStore/Managing Apps/AppManager.swift"
require_grep "Litter LocalDevVPN fallback treats active tunnel as detected" "Detected \(tunnelInterfaces.count) active tunnel interface" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_grep "KittyStore local source branded name" '"name": "KittyStore"' "ThirdParty/SideStore/Source/kittystore-source.json"
require_grep "KittyStore workflow source branded name" '"name": "KittyStore"' ".github/workflows/ios-unsigned-ipa.yml"
require_absent "KittyStore source metadata does not expose old ZYN branding" "ZYN" "ThirdParty/SideStore/Source/kittystore-source.json"
require_grep "KittyStore news cells brand fetched source text" "KittyStoreBranding.text(newsItem.title)" "ThirdParty/SideStore/Source/AltStore/News/NewsViewController.swift"
require_grep "KittyStore shared runtime branding helper" "enum KittyStoreBranding" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreBranding.swift"
require_grep "KittyStore tab bar fills bottom edge" "scrollEdgeAppearance" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore local source has app list" '"apps": [' "ThirdParty/SideStore/Source/kittystore-source.json"
require_grep "KittyStore embedded pairing help docs" "kittystore-pairing-file.md" "ThirdParty/SideStore/Source/AltStore/Settings/SettingsViewController.swift"
require_grep "KittyStore install failure propagation" "self.finish(.failure(error))" "ThirdParty/SideStore/Source/AltStore/Operations/SendAppOperation.swift"
require_absent "KittyStore install does not launch TurnOffData Shortcut" "TurnOffData" "ThirdParty/SideStore/Source/AltStore/Operations/SendAppOperation.swift"
require_absent "KittyStore install completion does not launch TurnOnDataDelay Shortcut" "TurnOnDataDelay" "ThirdParty/SideStore/Source/AltStore/Operations/InstallAppOperation.swift"
require_absent "KittyStore install path does not open Shortcuts app" "shortcuts://run-shortcut" "ThirdParty/SideStore/Source/AltStore/Operations/SendAppOperation.swift"
require_absent "KittyStore completion path does not open Shortcuts app" "shortcuts://run-shortcut" "ThirdParty/SideStore/Source/AltStore/Operations/InstallAppOperation.swift"
require_grep "KittyStore install failure identifies installation_proxy rejection" "installation_proxy rejected" "ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources/Install.swift"
require_grep "KittyStore My Apps deletes embedded self records" "embeddedHostApps(in: context)" "ThirdParty/SideStore/Source/AltStoreCore/Model/DatabaseManager/DatabaseManager.swift"
require_grep "KittyStore My Apps filters embedded self records" "excludingEmbeddedHostAppsPredicate" "ThirdParty/SideStore/Source/AltStoreCore/Model/InstalledApp.swift"
require_grep "KittyStore My Apps filters stale self record names" "embeddedHostNames" "ThirdParty/SideStore/Source/AltStoreCore/Model/InstalledApp.swift"
require_grep "KittyStore embedded runtime detection is shared" "InstalledApp.hidesEmbeddedHostApps" "ThirdParty/SideStore/Source/AltStoreCore/Model/DatabaseManager/DatabaseManager.swift"
require_grep "KittyStore My Apps skips self context menu" "isEmbeddedHostApp" "ThirdParty/SideStore/Source/AltStore/My Apps/MyAppsViewController.swift"
require_grep "KittyStore host matches embedded background" "KittyStoreHostPalette.background" "apps/ios/Sources/Litter/Views/KittyStoreHostView.swift"
require_grep "KittyStore embedded root uses SideStore background" ".altBackground" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore embedded transport startup" "startTransportIfPossible" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore sign-in falls back to imported pairing UDID" "storedPairingUDID" "ThirdParty/SideStore/Source/SideStore/MinimuxerWrapper.swift"
require_grep "KittyStore sign-in reads nested pairing record UDID" "PairRecordData" "ThirdParty/SideStore/Source/SideStore/MinimuxerWrapper.swift"
require_grep "KittyStore minimuxer RP pairing requires nested pair record" 'let hasRemotePairingRecord = pairingDict["PairRecordData"] is Data && pairingDict["private_key"] is Data' "ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources/Muxer.swift"
require_grep "KittyStore minimuxer accepts lockdown pairing by UDID" 'let hasLockdownPairingRecord = pairingDict["UDID"] is String' "ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources/Muxer.swift"
require_grep "KittyStore socket reset maps to LocalDevVPN error" "normalizedMinimuxerTransportError" "ThirdParty/SideStore/Source/SideStore/MinimuxerWrapper.swift"
require_grep "KittyStore install preflights minimuxer readiness" "ensureMinimuxerInstallTransportReady" "ThirdParty/SideStore/Source/SideStore/MinimuxerWrapper.swift"
require_grep "KittyStore lockdown install checks device connectivity" "Install: verifying device connectivity" "ThirdParty/SideStore/Source/Dependencies/minimuxer/Sources/Install.swift"
require_grep "KittyStore certificate import does not require system trust" "Password, private key, and certificate checks passed" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_grep "Litter minimuxer bridge uses runtime embedded bridge" "KittyStoreEmbeddedBridge.startMinimuxer" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_absent "Litter minimuxer bridge avoids Swift SideStore import autolink" "import SideStore" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_absent "Litter minimuxer bridge compile gate" "KITTYSTORE_MINIMUXER_LINKED" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_absent "Litter minimuxer bridge direct import" "import Minimuxer" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_grep "SideStore factory exposes minimuxer transport" "isMinimuxerTransportAvailable" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "SideStore factory exposes installed app browse" "installedAppsPlist" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "SideStore RustBridge exposes instproxy list apps" "rust_bridge_instproxy_list_apps" "ThirdParty/SideStore/Source/Dependencies/minimuxer/RustBridge/src/bridge.rs"

require_grep "KittyStore configurable release source" "AppReleaseSource.current" "apps/ios/Sources/Litter/Models/AppUpdateStore.swift"
require_grep "BuildKit configurable KittyStore source" "AppReleaseSource.current.stableSourceURLString" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_absent "hardcoded AppUpdateStore NightVibes repo URL" "github.com/NightVibes33/litter" "apps/ios/Sources/Litter/Models/AppUpdateStore.swift"
require_absent "hardcoded BuildKit KittyStore NightVibes repo URL" "github.com/NightVibes33/litter" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"

require_absent "BuildKit SideStore account UI scatter" "Import SideStore Account" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit Apple ID login UI scatter" "Login Apple ID" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit certificate import UI scatter" "Import SideStore Certificate" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit certificate handler scatter" "handleCertificateImport" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_grep "BuildKit keeps KittyStore login embedded" "Apple ID sign-in and 2FA stay inside KittyStore Settings" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit SideStore account handler scatter" "handleSideStoreAccountImport" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_absent "BuildKit Apple ID handler scatter" "saveNyxianAppleID" "apps/ios/Sources/Litter/Views/BuildKitSettingsView.swift"
require_grep "BuildKit binary pairing plist normalization" "normalizedPairingFileContents" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "LocalDevVPN endpoint reachability state" "endpointReachable" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_grep "Litter minimuxer bridge maps socket reset" "transportFailureLog" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_absent "overbearing LocalDevVPN interface dump" "Found active tunnel interface(s)" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_absent "overbearing minimuxer not-ready copy" "KittyStore minimuxer is linked but not ready yet" "apps/ios/Sources/Litter/Models/KittyStoreMinimuxerBridge.swift"
require_grep "BuildKit Apple ID LocalDevVPN gate" "LocalDevVPN is required for apple-id signing" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "KittyStore iOS SideStore scheme" "<string>sidestore</string>" "apps/ios/Sources/Litter/Info.plist"
require_grep "KittyStore iOS AltStore scheme" "<string>altstore</string>" "apps/ios/Sources/Litter/Info.plist"
require_grep "KittyStore iOS LocalDevVPN scheme" "<string>localdevvpn</string>" "apps/ios/Sources/Litter/Info.plist"
require_grep "SideStore LocalDevVPN override IP" "10.7.0.1" "apps/ios/Sources/KittyStoreEmbedded/KittyStoreEmbeddedFactory.swift"
require_grep "KittyStore minimuxer retarget wrapper" "retargetUsbmuxdAddr" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "KittyStore RustBridge CI build" "Building KittyStore RustBridge for iOS device" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore RustBridge static library staging" "librust_bridge.a" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore LocalDevVPN connection probe" "testLocalDevVPNConnection" "tools/scripts/build-sidestore-minimuxer.sh"
require_grep "SideStore local_user preservation" "local_user" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreAccountImport.swift"
require_grep "SideStore adiPB preservation" "adiPB" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreAccountImport.swift"
require_grep "SideStore ADI status" "hasSideStoreADI" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_absent "obsolete SideStore .sideconf bot command" "litter-kittystore-import-sideconf" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"

require_grep "SideStore bridge certificate validation" "kittystore-certificate-validation-failed" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_grep "SideStore imported certificate IPA preparation" "prepareSideStoreImportedIdentitySigningInput" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_grep "SideStore imported certificate accepts AltSign parser fallback" "validateWithAltSign" "apps/ios/Sources/Litter/Models/NyxianSigningCertificateValidator.swift"
require_grep "SideStore signing metadata rewrite" "CFBundleShortVersionString" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_absent "SideStore imported certificate direct IPA copy signing" "try fileManager.copyItem(at: ipaURL, to: outputURL)" "apps/ios/Sources/Litter/Models/KittyStoreSideStoreSigningBridge.swift"
require_grep "Feather remove files plan" "removeFiles" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_grep "Feather native remove files" "LBIKittyStoreRemoveAppFiles" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native appearance plist" "UIUserInterfaceStyle" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native minimum OS plist" "MinimumOSVersion" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native ProMotion plist" 'CADisableMinimumFrameDurationOnPhone"] = @YES' "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native injection path mapper" "LBIKittyStoreDylibLoadPath" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native inject into extensions" "LBIKittyStoreExtensionBundlePaths" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native injection failure status" "kittystore-dylib-injection-failed" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather native signed IPA bundle identifier artifact" '"bundleIdentifier": effectiveBundleID' "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"
require_grep "Feather BuildKit post-sign action executor" "applyKittyStorePostSigningActionIfNeeded" "apps/ios/Sources/Litter/Models/LitterBuildKit.swift"
require_absent "Feather native injection path unapplied warning" "recorded but not applied by this backend" "ThirdParty/Nyxian/LitterBuildKitNative/LitterBuildKitInProcess.mm"

require_absent "README obsolete SideStore .sideconf docs" ".sideconf" "README.md"
require_grep "README SideStore tab shape docs" "News, Sources, Browse, My Apps, and Settings" "README.md"
require_grep "README full SideStore source docs" "ThirdParty/SideStore/Source" "README.md"
require_grep "README full Feather source docs" "ThirdParty/Feather/Source" "README.md"
require_grep "README full LocalDevVPN source docs" "ThirdParty/SideStore/LocalDevVPN-Source" "README.md"
require_grep "Notices full SideStore source" "ThirdParty/SideStore/Source" "THIRD_PARTY_NOTICES.md"
require_grep "Notices full Feather source" "ThirdParty/Feather/Source" "THIRD_PARTY_NOTICES.md"
require_grep "Notices full LocalDevVPN source" "ThirdParty/SideStore/LocalDevVPN-Source" "THIRD_PARTY_NOTICES.md"
require_grep "README real LocalDevVPN launcher" "localdevvpn://" "README.md"
require_grep "README LocalDevVPN and pairing hard requirement" "direct install/refresh/remove/list operations stay blocked until LocalDevVPN is enabled and a pairing file is imported" "README.md"
require_grep "README SideStore/Feather attribution" "SideStore, AltStore, Feather, LocalDevVPN" "README.md"
require_grep "README installable AltSource versions" "version-history first" "README.md"
require_grep "Native container mount path" 'nativeContainerMountPath = "/mnt/container"' "apps/ios/Sources/Litter/Models/IshFS.swift"
require_grep "Native container bridge command" "repairNativeContainerBridge" "apps/ios/Sources/Litter/Models/IshFS.swift"
require_grep "Native container remount on launch" "repairNativeContainerBridgeOnReadyRuntime" "apps/ios/Sources/Litter/Models/LitterPlatform.swift"
require_grep "Native container mounted folders action" "Mount App Container" "apps/ios/Sources/Litter/Views/MountedFoldersView.swift"
require_grep "Native container file browser shortcut" "App Container" "apps/ios/Sources/Litter/Views/LocalFileWorkspaceView.swift"
require_grep "Native container file browser path" "IshFS.nativeContainerMountPath" "apps/ios/Sources/Litter/Views/LocalFileWorkspaceView.swift"

if [ "$missing" -ne 0 ]; then
  exit 1
fi

echo "KittyStore/Feather integration wiring verified."
