#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/litter"
KEYSTORE_PATH="${LITTER_UPLOAD_STORE_FILE:-$CONFIG_DIR/litter-upload.jks}"
CERT_PATH="${LITTER_UPLOAD_CERT_FILE:-$CONFIG_DIR/litter-upload-cert.pem}"
ENV_PATH="$CONFIG_DIR/upload-signing.env"
KEY_ALIAS="${LITTER_UPLOAD_KEY_ALIAS:-litter-upload}"
DNAME="${LITTER_UPLOAD_DNAME:-CN=Litter Upload, OU=Mobile, O=Sybil Solutions, C=US}"
STORE_PASSWORD_SERVICE="com.sigkitten.litter.android.upload-store-password"
KEY_PASSWORD_SERVICE="com.sigkitten.litter.android.upload-key-password"

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "This setup script stores signing passwords in the macOS login Keychain." >&2
    exit 1
fi

for command_name in keytool openssl security; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "Missing required command: $command_name" >&2
        exit 1
    fi
done

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

if [[ -e "$KEYSTORE_PATH" || -e "$CERT_PATH" || -e "$ENV_PATH" ]]; then
    echo "Refusing to overwrite existing Android upload-key material:" >&2
    [[ -e "$KEYSTORE_PATH" ]] && echo "  $KEYSTORE_PATH" >&2
    [[ -e "$CERT_PATH" ]] && echo "  $CERT_PATH" >&2
    [[ -e "$ENV_PATH" ]] && echo "  $ENV_PATH" >&2
    exit 1
fi

store_password="$(openssl rand -hex 24)"
key_password="$(openssl rand -hex 24)"

keytool -genkeypair \
    -keystore "$KEYSTORE_PATH" \
    -storepass "$store_password" \
    -alias "$KEY_ALIAS" \
    -keypass "$key_password" \
    -keyalg RSA \
    -keysize 4096 \
    -storetype JKS \
    -validity 9125 \
    -dname "$DNAME" \
    -noprompt

keytool -exportcert \
    -rfc \
    -keystore "$KEYSTORE_PATH" \
    -storepass "$store_password" \
    -alias "$KEY_ALIAS" \
    -file "$CERT_PATH"

security add-generic-password \
    -U \
    -a "$USER" \
    -s "$STORE_PASSWORD_SERVICE" \
    -w "$store_password" >/dev/null
security add-generic-password \
    -U \
    -a "$USER" \
    -s "$KEY_PASSWORD_SERVICE" \
    -w "$key_password" >/dev/null

{
    echo "# Generated by apps/android/scripts/setup-upload-key.sh"
    printf 'export LITTER_UPLOAD_STORE_FILE=%q\n' "$KEYSTORE_PATH"
    printf 'export LITTER_UPLOAD_KEY_ALIAS=%q\n' "$KEY_ALIAS"
    printf 'export LITTER_UPLOAD_STORE_PASSWORD="$(security find-generic-password -w -a "$USER" -s "%s")"\n' \
        "$STORE_PASSWORD_SERVICE"
    printf 'export LITTER_UPLOAD_KEY_PASSWORD="$(security find-generic-password -w -a "$USER" -s "%s")"\n' \
        "$KEY_PASSWORD_SERVICE"
} > "$ENV_PATH"
chmod 600 "$KEYSTORE_PATH" "$CERT_PATH" "$ENV_PATH"

unset store_password key_password

echo "Android upload key created."
echo "Keystore: $KEYSTORE_PATH"
echo "Public certificate for the Play upload-key reset: $CERT_PATH"
echo "Passwords are stored in the macOS login Keychain."
echo "The release script loads $ENV_PATH automatically."
